### ISSUE TITLE
mesa package and sub packages version 24.2.0-r0 causing failing builds in libreoffice

### ISSUE THREAD

**Issue by philroche** [wolfi-dev/os#27295]
See libreoffice package update PR @ https://github.com/wolfi-dev/os/pull/26543 with failing builds with error

```
2024/08/28 15:39:50 INFO checking for eglMakeCurrent in -lEGL... no
2024/08/28 15:39:50 WARN configure: error: libEGL required.
2024/08/28 15:39:50 WARN Error running configure at ./autogen.sh line 321.
```

I note there was an update to mesa 5 days ago

```
24.1.5-r0 (4 weeks ago - 2024-07-31 23:42:46 +0000 UTC) in wolfi os repository
24.2.0-r0 (6 days ago - 2024-08-23 02:42:21 +0000 UTC) in wolfi os repository
```

That update was part of mesa version bump PR https://github.com/wolfi-dev/os/pull/26346

If I revert mesa build time dependencies in the LibreOffice to version `24.1.5-r0 ` then build does succeed.

```
diff --git a/libreoffice-24.2.yaml b/libreoffice-24.2.yaml
index 3ef039444..fe57ec5cd 100644
--- a/libreoffice-24.2.yaml
+++ b/libreoffice-24.2.yaml
@@ -91,9 +91,11 @@ environment:
       - libxt-dev
       - libxtst-dev
       - m4
-      - mesa-dev
-      - mesa-egl
-      - mesa-gl
+      - mesa-dev=24.1.5-r0
+      - mesa-egl=24.1.5-r0
+      - mesa-gbm=24.1.5-r0
+      - mesa-gl=24.1.5-r0
+      - mesa-glapi=24.1.5-r0
       - nasm
       - openjdk-17
       - openjdk-17-default-jvm
```

Is there further changes required when depending on mesa, and subpackages, version 24.2.0-r0 or is this an issue in the new 24.2.0-r0 version? Was there a change in the ABI?

**Comment by philroche** [comment]
Related PR https://github.com/wolfi-dev/os/issues/27255 but not a dupe

**Comment by mamccorm** [comment]
meta should probably be version streamed? It isn't as obvious whats supported as there is no GitHub repo, but looking at the release note timestamps:
- https://docs.mesa3d.org/relnotes.html

They to seem to be currently supporting v24.1 and v24.2. v24.0. That said, even if we do version stream, we'd normally place in enterprise, which would mean libreoffice would not be able to access. We have made some exceptions in the past and added older versions in wolfi, whenever there were other dependencies

**Comment by mamccorm** [comment]
Also looks like 24.0.1 was cut and automerged a few minutes ago:
 - https://github.com/wolfi-dev/os/pull/27298/files

Might be worth re-testing libreoffice against 24.0.1

**Comment by philroche** [comment]
Assuming you meant `24.2.1`. The same build error with `24.2.1-r0`

```
2024/08/29 12:15:17 WARN configure: error: libEGL required.
2024/08/29 12:15:17 WARN Error running configure at ./autogen.sh line 321.
2024/08/29 12:15:17 ERRO ERROR: failed to build package. the build environment has been preserved:
```

**Comment by philroche** [comment]
Superseding libreoffice version bump PR https://github.com/wolfi-dev/os/pull/27736 build is failing due to the patch not being able to be applied cleanly but once patch is removed it fails in the same manner as previous version bump PR https://github.com/wolfi-dev/os/pull/26543  

```
2024/09/06 17:04:38 INFO checking for gtk+-3.0 >= 3.20 gtk+-unix-print-3.0 gmodule-no-export-2.0 glib-2.0 >= 2.38 atk >= 2.28.1 cairo... yes
2024/09/06 17:04:38 INFO checking for eglMakeCurrent in -lEGL... no
2024/09/06 17:04:38 WARN configure: error: libEGL required.
2024/09/06 17:04:38 WARN Error running configure at ./autogen.sh line 321.

```

**Comment by justinvreeland** [comment]
This has been solved for libreoffice with: https://github.com/wolfi-dev/os/pull/29745

and the underlying issue preventing the correct deps should be solved with: https://github.com/chainguard-dev/melange/commit/5b9c11e18bbc00366de20028162ca46629035b1f

**Comment by philroche** [comment]
@justinvreeland I am still seeing failures with build of LibreOffice @ https://github.com/wolfi-dev/os/pull/27736/ 

```
2024/10/04 16:50:23 INFO checking for eglMakeCurrent in -lEGL... no
2024/10/04 16:50:23 WARN configure: error: libEGL required.
```

Initially there are patch unable to apply failures but upon dropping the patch the libEGL errors are still present.

Even with the latest melange v0.13.0.

**Comment by smoser** [comment]
@philroche , close? since #27736 is merged?

**Comment by philroche** [comment]
Yup - we can close.
